
services:
  # --- RELACIJSKA BAZA (Uporabniki) ---
  db-users:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: user_password
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- STORITEV ZA UPORABNIKE ---
  user-service:
    build: ./user-service
    ports:
      - "8002:8000"  # User service bo zunaj dostopen na portu 8002
    depends_on:
      - db-users
    environment:
      DATABASE_URL: "postgresql://user_admin:user_password@db-users:5432/user_db"

  # --- DOCUMENT BAZA (IoT podatki) ---
  db-sensors:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017" # Pustimo odprto za tvoj direktni dostop (npr. Compass)
    volumes:
      - mongodb_data:/data/db

  # --- STORITEV ZA SENZORJE ---
  sensor-service:
    build: ./sensor-service
    ports:
      - "8001:8000" # Sensor service ostaja na 8001
    depends_on:
      - db-sensors
    environment:
      MONGODB_URL: "mongodb://db-sensors:27017"

  # --- CLOUDFLARE TUNNEL ---
  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token "eyJhIjoiMjg5NGRmOTI1ZTA4ZjU0ZDhkOGExOTczOTQ3YTcxYzciLCJ0IjoiNmI1YjA2MGMtYjNhYy00NmI5LWFkYTQtODFkMjVhMGU5YTNhIiwicyI6Ik1qWmpOMlF6TkdRdFlqWmxOaTAwTXpSa0xXRmpNMk10WmpBNVkyRXdNRGxtTVRFMiJ9"
    depends_on:
      - sensor-service
      - user-service

# DEFINICIJA VOLUMNOV (Ključno, da ne pride do errorja)
volumes:
  postgres_data:
  mongodb_data: